id: IAAF58793
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:10:25+00:00'
last_modified: '2022-06-08T12:07:22.200456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8532
  title: མཁྱེན་བརྩེ་དབང་པོ་དང་སྟག་བླ་ནོར་བུའི་སྨན་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AA2C:
      image_group_id: I1KG8565
      title: ''
      total_pages: 554
      order: 1
      base_file: AA2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
