id: P009592
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:43.516214
source_metadata:
  id: bdr:W1KG8532
  title: མཁྱེན་བརྩེ་དབང་པོ་དང་སྟག་བླ་ནོར་བུའི་སྨན་ཡིག
  author: ''
  volumes:
    619dbf8c28fc402fac7460b9ab1bdd23:
      image_group_id: I1KG8565
      title: ''
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
