id: P009592
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8532
  title: མཁྱེན་བརྩེ་དབང་པོ་དང་སྟག་བླ་ནོར་བུའི་སྨན་ཡིག
  author: ''
  volumes:
    619dbf8c28fc402fac7460b9ab1bdd23:
      image_group_id: I1KG8565
      title: ''
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
